import { resolve, join } from 'node:path';
import { existsSync, writeFileSync, unlinkSync, mkdirSync, readFileSync } from 'node:fs';
import { chmodSync } from 'node:fs';

import type { Command } from 'commander';

const PRE_COMMIT_SCRIPT = `#!/bin/sh
# Flint pre-commit hook — auto-generated by "flint hook install"
# Runs scenarios related to the staged commit.

COMMIT_MSG=$(git log -1 --pretty=%B 2>/dev/null || echo "")
SCENARIOS_DIR="\${FLINT_SCENARIOS_DIR:-./scenarios}"

if command -v flint >/dev/null 2>&1; then
  flint run --collections ./collections --env base "$SCENARIOS_DIR" 2>&1
  exit $?
fi

echo "[flint] flint command not found, skipping pre-commit check."
exit 0
`;

export function registerHookCommand(program: Command): void {
  const hook = program
    .command('hook')
    .description('Manage Flint git hooks');

  hook
    .command('install')
    .description('Install Flint pre-commit hook into .git/hooks/')
    .option('--force', 'overwrite existing hook without prompting')
    .action(async (opts: { force?: boolean }) => {
      const gitDir = findGitDir(process.cwd());
      if (!gitDir) {
        console.error('Not inside a git repository. Cannot install hook.');
        process.exit(1);
      }

      const hooksDir = join(gitDir, 'hooks');
      mkdirSync(hooksDir, { recursive: true });

      const hookPath = join(hooksDir, 'pre-commit');

      if (existsSync(hookPath) && !opts.force) {
        const existing = readFileSync(hookPath, 'utf8');
        if (existing.includes('flint hook')) {
          console.log('Flint pre-commit hook is already installed.');
          process.exit(0);
        }
        const answer = await prompt('pre-commit hook already exists. Overwrite? [y/N] ');
        if (answer.toLowerCase() !== 'y') {
          console.log('Aborted.');
          process.exit(0);
        }
      }

      writeFileSync(hookPath, PRE_COMMIT_SCRIPT, 'utf8');
      chmodSync(hookPath, 0o755);
      console.log(`\x1b[32m✓\x1b[0m Installed pre-commit hook at ${hookPath}`);
    });

  hook
    .command('remove')
    .description('Remove Flint pre-commit hook from .git/hooks/')
    .action(() => {
      const gitDir = findGitDir(process.cwd());
      if (!gitDir) {
        console.error('Not inside a git repository.');
        process.exit(1);
      }

      const hookPath = join(gitDir, 'hooks', 'pre-commit');

      if (!existsSync(hookPath)) {
        console.log('No pre-commit hook found.');
        process.exit(0);
      }

      const content = readFileSync(hookPath, 'utf8');
      if (!content.includes('flint')) {
        console.log('The existing pre-commit hook was not installed by Flint. Refusing to remove it.');
        process.exit(1);
      }

      unlinkSync(hookPath);
      console.log(`\x1b[32m✓\x1b[0m Removed pre-commit hook from ${hookPath}`);
    });
}

function findGitDir(startDir: string): string | null {
  let current = resolve(startDir);
  while (true) {
    const candidate = join(current, '.git');
    if (existsSync(candidate)) return candidate;
    const parent = resolve(current, '..');
    if (parent === current) return null;
    current = parent;
  }
}

function prompt(question: string): Promise<string> {
  return new Promise((resolve) => {
    process.stdout.write(question);
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    process.stdin.once('data', (data) => {
      process.stdin.pause();
      resolve(String(data).trim());
    });
  });
}
